services:
  monolog.formatter:
    class: Vainyl\Monolog\MonologLineFormatter
  monolog.instance.abstract:
    abstract: true
    class: Monolog\Logger
    calls:
      - [setFormatter, ['@monolog.formatter']]
  monolog.abstract:
    abstract: true
    class: Vainyl\Monolog\MonologLogger